apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: openshift-kube-scheduler-operator
  name: openshift-kube-scheduler-operator
  labels:
    app: openshift-kube-scheduler-operator
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
